### PR TITLE
fix for send-key-event not found

### LINKED ISSUE #90: boot command error - Unknown action: send-key-event
#### Overview of the Issue

When using the latest parallels plugin for packer and trying to create a vagrant box with a boot command option specified I get the following error:

`2023-08-09T12:39:34-05:00: ==> parallels-iso.vm: Error running boot command: prlctl error: Unknown action: send-key-event`

#### Reproduction Steps

HCL template for vagrant box using parallels plugin, run build

### Plugin and Packer version

Packer: 1.9.2
Packer-plugin-parallels: 1.1.1
Parallels: 18.3.2

### Simplified Packer Buildfile

Specifically trying to build this system https://github.com/chef/bento/blob/main/os_pkrvars/windows/windows-11-x86_64.pkrvars.hcl

### Operating system and Environment details

MacOS: 13.5 Intel cpu

### Log Fragments and crash.log files

[Github detailed format](https://gist.github.com/Stromweld/83cfc4eda046eb50220728a6ff8003bc)

### PR DESCRIPTION
**Pull request by sai-kumar-peddireddy**
Closes #90

### CODE REVIEW

**Review by cjlapao — APPROVED** [review]

**Comment by Stromweld** [comment]
@cjlapao is this going to be released soon as this is a big bug that makes current 1.1.1 release unusable if using a boot command.

**Comment by sai-kumar-peddireddy** [comment]
@Stromweld Already triggered the release job, it will be released in 5 min

**Comment by cjlapao** [comment]
@Stromweld the release is underway. Should be available in the next 30 minutes

**Comment by sai-kumar-peddireddy** [comment]
@Stromweld release is live now, you can use it

**Comment by Stromweld** [comment]
Thank you very much, confirmed that it is working now.

**Comment by sai-kumar-peddireddy** [comment]
Thanks for reporting the issue

**Pull request merged**
